#### Site Settings ###
title               : Nicholas Jonathan
description         : >-                               # >- means to ignore newlines until "url:"
                      "Work In Progress. Go watch some doctor who you nerd. Jk I actually love doctor who."

baseurl             : "/testing"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
#repository          : Seerow0/Seerow0.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
#repository          :    # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
# remote_theme        : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only
  - documentation/docs.md
  - documentation/elements.html
  - pages/blog.html
  - documentation/04-adding-content/08-timeline-events.md
  - documentation/04-adding-content/02-remote-projects.md
### Author Info ###
author:
  name              : Nicholas Jonathan
 # image             : "/images/southpark.jpg?raw=true"
  image             : "https://raw.githubusercontent.com/Seerow0/web2/main/images/calcifer.png"
# behance           : your_username
# dribbble          : your_username
  email             : #its in social media file| if you put it here, it will fail since its already in socialmedia|same for github and linkedin
# facebook          : your_username
  github            : 
# gitlab            : your_username
  #instagram         : your_username
  linkedin          :
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name



### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  research:
    output: true
    permalink: /research/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee: 
  enabled: true
  username: nicholasjv14
  color: "#8400ff"
  #message: "These aren't the droids you're looking for." # Message to be displayed aside from the button for a few seconds.
  description: "Give Me Rent Spiderman!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
